version: "3.8"

services:
  app:
    image: dbdemo:test
    container_name: myapp
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0.45-debian
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: test
    ports:
      - "3326:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

